### PR TITLE
ignore test.md

### PR DESCRIPTION
**Pull request by RokoVarano**
my first pull request

### CODE REVIEW

**Comment by vicmaburrito** [comment]
the linters have not been set up correctly for this repository and the new of the branch is not descriptive

**Comment by RokoVarano** [comment]
> the linters have not been set up correctly for this repository and the new of the branch is not descriptive

I have not understood how to do this, I will ask for help in the afternoon stand up

**Comment by RokoVarano** [comment]
> the linters have not been set up correctly for this repository and the new of the branch is not descriptive

I have changed the name of the branch

**Comment by vicmaburrito** [comment]
Ok my friend

**Pull request merged**
